# Generated by Django 3.2.20 on 2023-11-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0152_readthrough_stopped_date_remove"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="readthrough",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("finish_date__isnull", False),
                    ("read_status", "reading"),
                    _negated=True,
                ),
                name="currently-reading",
            ),
        ),
        migrations.AddConstraint(
            model_name="readthrough",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("read_status", "to-read"), _negated=True),
                    models.Q(
                        ("finish_date__isnull", True), ("start_date__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="to-read",
            ),
        ),
    ]
